@startuml
title Warmhouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы Умный дом")
Person(admin, "Administrator", "Администратор системы")
System(Warmhouse, "Warmhouse System", "Система управлением отопления и мониторинга температуры")

System_Ext(SmartDevices, "Smart Devices", "Умные устройства партнеров")

Rel(user, Warmhouse, "Использование системы")
Rel(admin, Warmhouse, "Администрирование системы")
Rel(Warmhouse, SmartDevices, "Подключение устройств")

@enduml