@startuml
title Warmhouse Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы Умный дом")
Person(admin, "Administrator", "Администратор системы")
System(Warmhouse, "Warmhouse System", "Система управления умного дома")


Container_Boundary(Warmhouse, "Warmhouse System") {
  Container(WebApp, "Web Application", "Java, Spring", "Обработка запросов пользователя")
  Container(UserService, "User Service", "Go", "Управление данными пользователя")
  Container(MonitoringService, "Monitoring Service", "Go", "Мониторинг температуры")
  Container(DevicesService, "Devices Service", "Go", "Управление устройствами")
  SystemDb(UserDatabase, "User Database", "PostgreSQL", "Данные о пользователе")
  SystemDb(DevicesDatabase, "Devices Database", "PostgreSQL", "Данные об устройствах")
  SystemDb(MonitoringDatabase, "Monitoring Database", "PostgreSQL", "Данные о мониоринге показателей")
}

System_Ext(SmartDevices, "Smart Devices", "Умные устройства партнеров")

Rel(user, WebApp, "Использует систему")
Rel(admin, WebApp, "Управляет системой")
Rel(WebApp, UserService, "Запросы данных о пользователе")
Rel(WebApp, DevicesService, "Запросы на подключение/отключение/изменение устройств")
Rel(WebApp, MonitoringService, "Запросы на получение показателей датчиков")
Rel(UserService, UserDatabase, "Чтение/запись данных о пользователе")
Rel(DevicesService, DevicesDatabase, "Чтение/запись данных об устройствах")
Rel(MonitoringService, MonitoringDatabase, "Чтение данных о показателях датчиков")
Rel(DevicesService, SmartDevices, "Подключение устройств партнеров")
@enduml