@startuml
title Warmhouse Devices Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class Device {
  +UUID ID
  +String Name
  +String Status
  +Date UpdatedAt
  +Date CreatedAt
  +void get()
  +void update()
  +void delete()
  +void create()
}

class DeviceType {
    +UUID ID
    +String name
    +String manufacturer
    +String protocol
    +void get()
}

class Location {
    +UUID ID
    +String name
    +void get()
}

Device "1" -- "0..*" DeviceType : has
Device "1" -- "0..*" Location : has

@enduml