@startuml
title Warmhouse Web Application Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(Warmhouse, "Warmhouse System") {
  Container(UserService, "User Service", "Go", "Управление данными пользователя")
  SystemDb(UserDatabase, "User Database", "PostgreSQL", "Данные о пользователе")
}

Container(UserService, "User Service", "Go") {
  Component(UserController, "UserController", "Manages user profiles")
  Component(AuthController, "AuthController", "Manages devices")
  Component(ServiceLayer, "Service Layer", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(UserController,ServiceLayer,"Calls business logic")
Rel(AuthController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,RepositoryLayer,"Reads/Writes data")
Rel(RepositoryLayer,UserDatabase,"Reads/Writes user data")
@enduml