@startuml
title Warmhouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы Умный дом")
Person(admin, "Administrator", "Специалист по подключению к системе")
System(Warmhouse, "Warmhouse System", "Система управлением отопления и мониторинга температуры")

System_Ext(HeatingSystem, "Heating System", "Система отопления (датчики)")

Rel(user, Warmhouse, "Включение/выключение отопления")
Rel(user, Warmhouse, "Мониторинг температуры")
Rel(admin, Warmhouse,"Подключение датчиков к системе")
Rel(Warmhouse, HeatingSystem, "Запрос на получение температуры\nЗапрос на включение/выключение отопления")
Rel(HeatingSystem, Warmhouse, "Значения температуры\nСтатус выполгнения запроса")

@enduml