@startuml

entity User {
    * user_id : UUID
    --
    email : string
    name : string
    passwordHash : string
    createdAt : timestamp
    createdAt : timestamp
}

entity Location {
    * location_id : UUID
    --
    name : string
}

entity DeviceType {
    * device_type_id : UUID
    --
    user_id : UUID
    name : string
    manufacturer : string
    protocol : string
}

entity Device {
    * device_id : UUID
    --
    location_id : UUID
    deviceType_id : UUID
    serialNumber : string
    name : string
    status : string
}

entity MonitoringData {
    * monitoring_id : UUID
    --
    user_id : UUID
    metric : string
    value : string
    unit : string
    timestamp : timestamp
}

User ||--o{ Device

Location ||--o{ Device

DeviceType ||--o{ Device

User ||--o{ MonitoringData

@enduml